[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Dennis Yao <omethyn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2"
itertools = "0.9.0"
num = "0.3"
lazy_static = "1.4.0"
